Add auto install yad command to main

diff --git a/main b/main
--- a/main
+++ b/main
@@ -7,6 +7,19 @@ function error {
   exit 1
 }
 
+#install yad automatically
+if ! command -v yad >/dev/null;then
+  if [ -f /usr/bin/apt ];then
+    sudo apt update
+    sudo apt install -y yad || error "Failed to install yad."
+    updated=1
+  else
+    error "Failed to find any package manager to install yad."
+  fi
+fi
+#remove annoying YAD icon browser launcher
+sudo rm -f /usr/share/applications/yad-icon-browser.desktop
+
 #$1 is usually left blank. if so, open gui
 if [ "$1" == '' ];then
   #Run gui script
